baseurl: ''
url: 'https://jmap.io'
markdown: kramdown
lightningcss:
    targets: defaults
esbuild:
    target: es2022
exclude:
    - package.json
    - package-lock.json
    - prettier.config.mjs
    - stylelint.config.js
    - README.md
