baseurl: ''
url: 'https://jmap.io'
markdown: kramdown
lightningcss:
    targets: defaults
esbuild:
    target: es2022
exclude:
    - package.json
    - package-lock.json
    - prettier.config.mjs
    - stylelint.config.js
    - README.md
collections_dir: _collections
collections:
    combomark:
        output: true
        order:
            - jmap-combination-mark-light.liquid
            - jmap-combination-mark-dark.liquid
    logomark:
        output: true
        order:
            - jmap-logomark-light.liquid
            - jmap-logomark-dark.liquid
