baseurl: ''
url: 'http://jmap.io'
markdown: kramdown
lightningcss:
  targets: defaults
esbuild:
  target: es2022
exclude:
  - _tmp
  - _bin
  - scripts
  - vendor
  - package.json
  - package-lock.json
  - prettier.config.mjs
  - stylelint.config.js
